export const ADD_POST = 'APP/ADD_POST'
export const SHOW_MODAL = 'APP/SHOW_MODAL'
export const HIDE_MODAL = 'APP/HIDE_MODAL '
export const START_LOADING = 'APP/START_LOADING'
export const END_LOADING = 'APP/END_LOADING'
export const LOAD_POSTS = 'APP/LOAD_POSTS'
export const APP_LOADING = 'APP/LOADING'
export const APP_LOADED = 'APP/LOADED'
export const USER_SINGED_IN = 'APP/USER_SINGED_IN'
export const USER_SINGED_OUT = 'APP/USER_SINGED_OUT'

export const SET_AUTH_TO_TRUE = 'USER/SET_AUTH_TO_TRUE'
export const SET_AUTH_TO_FASLE = 'USER/SET_AUTH_TO_FALSE'

export const SHOW_ALERT = 'APP/SHOW_ALERT'
export const HIDE_ALERT = 'APP/SHOW_ALERT'

export const SET_POSTS = 'POSTS/SET_POSTS'

export const CHANGE_RATIO = 'POST/CHANGE_RATIO'

export const CHANGE_CONFIRM_MODAL = 'DRAWLER/CAHNGE_CONFIRM_MODAL'

export const ADD_IMAGE_TO_NEW_POST = 'DRAWLER/ADD_IMAGE_TO_NEW_POST'

export const REMOVE_IMAGE_FROM_NEW_POST = 'DRAWLER/ADD_IMAGE_TO_NEW_POST'

export const CLEAR_IMAGE_FROM_NEW_POST = 'DRAWLER/CLEAR_IMAGE_FROM_NEW_POST'

export const ADD_CROPPED_IMAGE_TO_NEW_POST = 'DRAWLER/ADD_CROPPED_IMAGE_TO_NEW_POST'

export const REMOVE_CROPPED_IMAGE_FROM_NEW_POST = 'DRWLWER/REMOBE_CROPPED_IMAGE_TO_NEW_POST'

export const CLEAR_CROPPED_IMAGE_FROM_NEW_POST = 'DRAWLER/CLEAR_CROPPED_IMAGE_FROM_NEW_POST'

export const CHANGE_DRAWLER_CONTROLLER = 'DRAWLER/CHANGE_DRAWLER_CONTROLLER'

export const AUTH_LOADED = 'APP/AUTH_LOADED'

export const CHANGE_STEP_OF_POST = 'APP/CHANGE_STEP_OF_POST'

export const CHANGE_LOADER_MODAL = 'APP/CHANGE_LOADER_MODAL'

export const OPEN_POST_DETAIL_MODAL = 'POST/OPEN_POST_DETAIL_MODAL'
export const CLOSE_POST_DETAIL_MODAL = 'POST/CLOSE_POST_DETAIL_MODAL'

export const SELECT_POST_DETAIL_MODAL_POST = 'POST/SELECT_POST_DETAIL_MODAL_POST'