export { default as Home }  from './Home'
export { default as SignIn } from './auth/Signin'
export { default as SignUp } from './auth/register'
export { default as ChatRoom } from './ChanRoom'
export { default as Chats } from './Chats'
export { default as Photos } from './Photos'
export { default as Profile } from './Profile'