export { default as Photo1_1Icon } from './Photo1_1Icon'
export { default as Photo4_5Icon } from './Photo4_5Icon'
export { default as PhotoIcon } from './PhotoIcon'
export { default as Photo16_9Icon } from './Photo16_9'
export { default as ArrowBackIcon } from './ArrowBackIcon'
export { default as Smile } from './Smile'
export { default as Location } from './Location'
export { default as Chevron } from './Chavron'

export { default as PaperFlyIcon } from './post/PaperFly'
export { default as BooKMarkIcon } from './post/BookMark'
export { default as BooKMarkFilled } from './post/BookMarkFilled'
export { default as ChatIcon } from './post/ChatIcon'
export { default as FilledHeart } from './post/FilledHeart'

export { default as AddIcon } from './header/AddIcon'
export { default as CompasIcon } from './header/Compas'
export { default as CompasFilled } from './header/CompassFileed'
export { default as HeartIcon } from './header/Heart'
export { default as HomeIcon } from './header/Home'
export { default as HomeFilled } from './header/HomeFillled'
export { default as MessageIcon } from './header/MessagesIcon'
export { default as MessaagesFilled } from './header/MessagesFiled'
